#!/usr/bin/bash
# Perform duckduckgo bang search

HISTORY_LENGTH=30
QUERY="duckduckgo.com/?q=%s"
BROWSER="firefox"

# Make history file
if [ ! -x "$HOME/.bang_history" ]
then
	touch "$HOME/.bang_history"
fi

# If there aren't 0 arguments
# (search passed through $@)
if [ ! $# -eq 0 ]
then
	# If this search is in the file, delete the line containing it
	if grep "$@" $HOME/.bang_history
	then
		sed -i "/^$@$/Id" $HOME/.bang_history
	fi

	# Append this to end of history
	echo "$@" >> $HOME/.bang_history

	# Trim history to last $HISTORY_LENGTH entries
	tail -n +$HISTORY_LENGTH $HOME/.bang_history

	# Open formatted query in browser
	FORMATTED_QUERY=$(printf $QUERY "$(echo $@ | sed 's/ /\ /g')")
	$BROWSER "$FORMATTED_QUERY"

	exit 0
fi

# By default, the search is input into rofi
cat $HOME/.bang_history
