#!/usr/bin/bash
# Installs themes

# Used to store certain states
mkdir -p $HOME/.config

# Set gtk themes
gsettings set org.gnome.desktop.interface gtk-theme "Gruvbox-Material-Dark"
gsettings set org.gnome.desktop.interface icon-theme "Gruvbox-Material-Dark"
gsettings set org.gnome.desktop.interface font-name "FreeSans 10"
gsettings set org.gnome.desktop.interface document-font-name "FreeSans 10"
gsettings set org.gnome.desktop.interface monospace-font-name "Iosevka 10"

# Copy configs to config directory
SCRIPT_DIR=$(dirname $0)
CONFIG_DIR=$SCRIPT_DIR/../config
WALLPAPER_DIR=$SCRIPT_DIR/../wallpapers

# $1 - From directory
# $2 - To directory
sync () {
	# Sync new file
	rsync -ar $1 $2
	rename 'dot-' '.' $2*
}

for config in $(ls -A $CONFIG_DIR); do
	echo "Syncing config/$config"
	sync $CONFIG_DIR/$config $HOME/.config/
done

# Set wallpaper if it hasn't been set already
if [ ! -f "$HOME/.wallpaper" ]; then
	echo "Setting wallpaper for the first time..."	
	$SCRIPT_DIR/set-wallpaper.sh WALLPAPER_DIR/default_wallpaper.png
fi

echo "Done!"
