#!/usr/bin/bash
# Installs packages from the package list

SCRIPT_DIR=$(dirname $0)
SERVICE_DIR=$SCRIPT_DIR/../services

# Update all packages
awk '{print $1}' $SCRIPT_DIR/../install/packages | sudo xargs pacman -Syyu --noconfirm

# Install AUR packages
for package in $(awk '{print $1}' $SCRIPT_DIR/../install/aurpackages); do 
	cd /tmp/
	git clone https://aur.archlinux.org/$package.git
	cd $package
	git pull
	makepkg -si --noconfirm
done

# Download repositories
for repo in $(awk '{print $1}' $SCRIPT_DIR/../install/repositories); do 
	cd /tmp/
	git clone $repo
	dir=basename $repo | awk -F'[_.]' '{print $(NF-1)}'
	cd $dir
	git pull
done

# Set defaults
cat $SCRIPT_DIR/../install/defaults | while read line 
do
	echo $line
	xdg-mime default $line
done

# Add custom user services
for service in $SERVICE_DIR/*; do
	sudo cp $service /etc/systemd/system/$(basename $service)
done

# Add ly configuration for pam.d
sudo cp $SCRIPT_DIR/etc/ly /etc/pam.d/ly

# Add default user to light group
sudo usermod -aG video $USER

# Enable the slock service
sudo systemctl enable slock@$USER.service

# Make ly the default login manager
sudo systemctl enable ly.service

echo "Done!"
