#!/usr/bin/bash
# Installs packages from the package list

SCRIPT_DIR=$(dirname $0)
SERVICE_DIR=$SCRIPT_DIR/../services

awk '{print $1}' $SCRIPT_DIR/../install/packages | sudo xargs pacman -Syyu --noconfirm

# Install AUR packages
for package in $(awk '{print $1}' $SCRIPT_DIR/../install/aurpackages); do 
	cd /tmp/
	git clone https://aur.archlinux.org/$package.git
	cd $package
	git pull
	makepkg -si --noconfirm
done

# Set defaults
cat $SCRIPT_DIR/../install/defaults | while read line 
do
	echo $line
	xdg-mime default $line
done

# Add custom user services
for service in $SERVICE_DIR/*; do
	sudo cp $service /etc/systemd/system/$(basename $service)
done

# Add default user to light group
sudo usermod -aG video $USER

# Enable the slock service
sudo systemctl enable slock@$USER.service

# Make ly the default login manager
sudo systemctl enable ly.service

echo "Done!"
